INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Acre','AC');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Alagoas','AL');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Amapá','AP');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Amazonas','AM');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Bahia','BA');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Ceará','CE');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Distrito Federal','DF');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Espírito Santo','ES');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Goiás','GO');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Maranhão','MA');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Mato Grosso','MT');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Mato Grosso do Sul','MS');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Minas Gerais','MG');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Pará','PA');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Paraíba','PB');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Paraná','PR');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Pernambuco','PE');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Piauí','PI');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Rio de Janeiro','RJ');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Rio Grande do Norte','RN');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Rio Grande do Sul','RS');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Rondônia','RO');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Roraima','RR');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Santa Catarina','SC');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'São Paulo','SP');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Sergipe','SE');
INSERT INTO estado (id_pais, descricao, sigla) VALUES(1, 'Tocantins','TO');